In [26]:
import pandas as pd
import os
import json
import glob
import sqlite3
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
#ouvert les paramètres décrits dans le fichier JSON
with open('../parameters.json') as json_data:
    params = json.load(json_data)

In [3]:
#utilisation des paramètres pour créer un DATA et TMP
DATA_DIR = params['DIRECTORIES']['DATA_DIR']
TMP_DIR = params['DIRECTORIES']['TMP_DIR']
PRICE_FILE = params['FILES']['PRICE_FILE']
STATION_FILE = params['FILES']['STATION_FILE']
SERVICE_FILE = params['FILES']['SERVICE_FILE']
GAS_DB = os.path.join(DATA_DIR, params['DATABASE']['GAS_DB'])

In [4]:
dfall = pd.read_pickle(os.path.join(DATA_DIR,PRICE_FILE))
dfservices = pd.read_pickle(os.path.join(DATA_DIR, SERVICE_FILE))
dfstations = pd.read_pickle(os.path.join(DATA_DIR, STATION_FILE))

In [5]:
dfall['date_releve'] = pd.to_datetime(dfall.date_releve)

In [6]:
moyenne_hebdo_df = (dfall
    .dropna(subset=['date_releve'])
    .groupby(['libelle_carburant', pd.Grouper(key = "date_releve", freq ="2W-MON" )])
    .agg({'prix': np.mean})
                   ).reset_index()

In [18]:
model_df=(dfall
    .dropna(subset=['date_releve'])
    .groupby(["id_station",'libelle_carburant', "code_postal", "type_station", pd.Grouper(key = "date_releve", freq ="2W-MON" )])
    .agg({'prix': np.mean})
    .reset_index()
    .merge(moyenne_hebdo_df, how='inner', on=["libelle_carburant", "date_releve"], suffixes=("", "_moyen"))
    .assign(indice= lambda _df: _df['prix']/ _df["prix_moyen"])
                   )

In [19]:
model_df.shape

(1967200, 8)

In [22]:
model_df.indice.describe()

count    1.967200e+06
mean     1.006113e+00
std      4.895929e-02
min      1.433393e-03
25%      9.751991e-01
50%      9.920516e-01
75%      1.035401e+00
max      2.046148e+00
Name: indice, dtype: float64

In [28]:
vectorize = CountVectorizer(tokenizer= lambda x: x.split(','), lowercase=False)
vectorize.fit_transform(dfservices.services.fillna('Rien'))

<12391x25 sparse matrix of type '<class 'numpy.int64'>'
	with 75115 stored elements in Compressed Sparse Row format>

In [32]:
matrice_services_df = pd.SparseDataFrame(vectorize.fit_transform(dfservices.services.fillna('rien')),
                  dfservices.id_station,
                  vectorize.get_feature_names(),
                  default_fill_value=0).reset_index()

In [36]:
model_df.merge(matrice_services_df, how='inner', on=['id_station'], indicator=True)

,id_station,libelle_carburant,code_postal,type_station,date_releve,prix,prix_moyen,indice,Aire de camping-cars,Automate CB,...,Restauration sur place,Restauration à emporter,Station de gonflage,Station de lavage,Toilettes publiques,Vente de fioul domestique,Vente de gaz domestique,Vente de pétrole lampant,rien,_merge
0,1000001,E10,01000,R,2015-02-16,1309.000000,1322.061275,0.990121,0,1,...,0,0,1,0,0,0,1,0,0,both
1,1000001,Gazole,01000,R,2014-01-06,1304.000000,1339.424795,0.973552,0,1,...,0,0,1,0,0,0,1,0,0,both
2,1000001,Gazole,01000,R,2014-01-20,1304.000000,1327.212038,0.982511,0,1,...,0,0,1,0,0,0,1,0,0,both
3,1000001,Gazole,01000,R,2014-02-03,1302.000000,1323.991679,0.983390,0,1,...,0,0,1,0,0,0,1,0,0,both
4,1000001,Gazole,01000,R,2014-02-17,1287.000000,1324.761090,0.971496,0,1,...,0,0,1,0,0,0,1,0,0,both
5,1000001,Gazole,01000,R,2014-03-03,1307.727273,1330.106289,0.983175,0,1,...,0,0,1,0,0,0,1,0,0,both
6,1000001,Gazole,01000,R,2014-03-17,1285.000000,1319.265994,0.974026,0,1,...,0,0,1,0,0,0,1,0,0,both
7,1000001,Gazole,01000,R,2014-03-31,1302.800000,1305.573039,0.997876,0,1,...,0,0,1,0,0,0,1,0,0,both
8,1000001,Gazole,01000,R,2014-04-14,1266.142857,1302.705430,0.971933,0,1,...,0,0,1,0,0,0,1,0,0,both
9,1000001,Gazole,01000,R,2014-04-28,1273.500000,1304.522353,0.976219,0,1,...,0,0,1,0,0,0,1,0,0,both
10,1000001,Gazole,01000,R,2014-05-12,1274.000000,1307.050671,0.974714,0,1,...,0,0,1,0,0,0,1,0,0,both
11,1000001,Gazole,01000,R,2014-05-26,1274.000000,1306.691994,0.974981,0,1,...,0,0,1,0,0,0,1,0,0,both
12,1000001,Gazole,01000,R,2014-06-09,1272.600000,1300.610770,0.978463,0,1,...,0,0,1,0,0,0,1,0,0,both
13,1000001,Gazole,01000,R,2014-06-23,1271.600000,1314.533167,0.967340,0,1,...,0,0,1,0,0,0,1,0,0,both
14,1000001,Gazole,01000,R,2014-07-07,1287.000000,1321.061279,0.974217,0,1,...,0,0,1,0,0,0,1,0,0,both
15,1000001,Gazole,01000,R,2014-07-21,1268.538462,1297.444514,0.977721,0,1,...,0,0,1,0,0,0,1,0,0,both
16,1000001,Gazole,01000,R,2014-08-04,1274.000000,1294.251979,0.984352,0,1,...,0,0,1,0,0,0,1,0,0,both
17,1000001,Gazole,01000,R,2014-08-18,1274.000000,1297.710608,0.981729,0,1,...,0,0,1,0,0,0,1,0,0,both
18,1000001,Gazole,01000,R,2014-09-01,1274.000000,1293.806667,0.984691,0,1,...,0,0,1,0,0,0,1,0,0,both
19,1000001,Gazole,01000,R,2014-09-15,1262.800000,1285.261266,0.982524,0,1,...,0,0,1,0,0,0,1,0,0,both
20,1000001,Gazole,01000,R,2014-09-29,1264.800000,1286.650147,0.983018,0,1,...,0,0,1,0,0,0,1,0,0,both
21,1000001,Gazole,01000,R,2014-10-13,1249.000000,1280.695925,0.975251,0,1,...,0,0,1,0,0,0,1,0,0,both
22,1000001,Gazole,01000,R,2014-10-27,1212.333333,1253.701808,0.967003,0,1,...,0,0,1,0,0,0,1,0,0,both
23,1000001,Gazole,01000,R,2014-11-10,1212.000000,1239.912698,0.977488,0,1,...,0,0,1,0,0,0,1,0,0,both
24,1000001,Gazole,01000,R,2014-11-24,1205.500000,1235.297997,0.975878,0,1,...,0,0,1,0,0,0,1,0,0,both
25,1000001,Gazole,01000,R,2014-12-08,1164.666667,1199.196604,0.971206,0,1,...,0,0,1,0,0,0,1,0,0,both
26,1000001,Gazole,01000,R,2014-12-22,1105.200000,1140.303553,0.969216,0,1,...,0,0,1,0,0,0,1,0,0,both
27,1000001,Gazole,01000,R,2015-01-05,1097.666667,1114.581039,0.984824,0,1,...,0,0,1,0,0,0,1,0,0,both
28,1000001,Gazole,01000,R,2015-01-19,1105.333333,1117.493738,0.989118,0,1,...,0,0,1,0,0,0,1,0,0,both
29,1000001,Gazole,01000,R,2015-02-02,1089.166667,1109.652086,0.981539,0,1,...,0,0,1,0,0,0,1,0,0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1955164,40530005,GPLc,40530,A,2015-02-02,869.000000,815.244645,1.065938,0,0,...,0,0,1,0,1,0,0,0,0,both
1955165,75016003,SP98,75016,R,2016-08-01,1599.000000,1350.945283,1.183616,0,0,...,0,0,1,0,0,0,1,0,0,both
1955166,92200003,SP98,92200,R,2016-08-01,1599.000000,1350.945283,1.183616,0,0,...,0,0,1,0,1,0,1,0,0,both
1955167,87160006,GPLc,87160,A,2015-12-21,777.000000,755.201102,1.028865,0,0,...,1,1,1,0,1,0,0,0,0,both
1955168,87160006,GPLc,87160,A,2016-01-04,783.000000,748.397551,1.046235,0,0,...,1,1,1,0,1,0,0,0,0,both
1955169,87160006,GPLc,87160,A,2014-01-20,950.000000,857.415053,1.107981,0,0,...,1,1,1,0,1,0,0,0,0,both
1955170,87160006,GPLc,87160,A,2016-05-23,783.000000,700.792639,1.117306,0,0,...,1,1,1,0,1,0,0,0,0,both
1955171,87160006,GPLc,87160,A,2015-01-19,890.000000,832.551672,1.069003,0,0,...,1,1,1,0,1,0,0,0,0,both
1955172,87160006,GPLc,87160,A,2015-09-14,833.000000,781.789474,1.065504,0,0,...,1,1,1,0,1,0,0,0,0,both
1955173,68200003,E10,68200,R,2014-01-06,1430.000000,1490.073267,0.959684,0,0,...,0,0,0,0,0,0,1,0,0,both
1955174,58140002,GPLc,58140,R,2015-03-02,873.000000,806.901786,1.081916,0,0,...,0,0,0,0,0,0,0,0,0,both
1955175,58140002,GPLc,58140,R,2014-05-12,873.000000,856.423981,1.019355,0,0,...,0,0,0,0,0,0,0,0,0,both
1955176,58140002,GPLc,58140,R,2016-01-18,873.000000,735.008015,1.187742,0,0,...,0,0,0,0,0,0,0,0,0,both
1955177,58140002,GPLc,58140,R,2016-02-01,767.000000,733.032280,1.046339,0,0,...,0,0,0,0,0,0,0,0,0,both
1955178,74600012,GPLc,74600,A,2016-01-04,780.000000,748.397551,1.042227,0,0,...,0,0,1,0,0,0,0,0,0,both
1955179,74600012,GPLc,74600,A,2017-01-02,820.000000,716.324960,1.144732,0,0,...,0,0,1,0,0,0,0,0,0,both
1955180,74600012,GPLc,74600,A,2014-01-20,950.000000,857.415053,1.107981,0,0,...,0,0,1,0,0,0,0,0,0,both
1955181,74600012,GPLc,74600,A,2015-07-06,869.000000,791.278512,1.098223,0,0,...,0,0,1,0,0,0,0,0,0,both
1955182,53100006,GPLc,53100,R,2016-02-15,619.000000,733.266767,0.844168,0,0,...,0,0,1,0,0,0,0,0,0,both
1955183,53100006,GPLc,53100,R,2014-03-17,799.000000,859.357614,0.929764,0,0,...,0,0,1,0,0,0,0,0,0,both
1955184,53100006,GPLc,53100,R,2015-07-06,659.000000,791.278512,0.832829,0,0,...,0,0,1,0,0,0,0,0,0,both
1955185,53100006,GPLc,53100,R,2016-01-18,659.000000,735.008015,0.896589,0,0,...,0,0,1,0,0,0,0,0,0,both
1955186,53100006,GPLc,53100,R,2016-09-12,619.000000,695.008593,0.890636,0,0,...,0,0,1,0,0,0,0,0,0,both
1955187,53100006,GPLc,53100,R,2016-10-10,619.000000,700.382961,0.883802,0,0,...,0,0,1,0,0,0,0,0,0,both
1955188,53100006,GPLc,53100,R,2015-01-05,799.000000,838.124484,0.953319,0,0,...,0,0,1,0,0,0,0,0,0,both
1955189,53100006,GPLc,53100,R,2015-01-19,774.000000,832.551672,0.929672,0,0,...,0,0,1,0,0,0,0,0,0,both
1955190,53100006,GPLc,53100,R,2015-02-16,689.000000,821.327984,0.838885,0,0,...,0,0,1,0,0,0,0,0,0,both
1955191,53100006,GPLc,53100,R,2015-08-17,659.000000,793.353084,0.830652,0,0,...,0,0,1,0,0,0,0,0,0,both
1955192,53100006,GPLc,53100,R,2015-10-26,659.000000,766.522339,0.859727,0,0,...,0,0,1,0,0,0,0,0,0,both
1955193,69380011,GPLc,69380,A,2016-07-04,777.000000,718.403846,1.081564,0,0,...,1,1,1,0,1,0,0,0,0,both

In [39]:
(model_df
.merge(matrice_services_df,how='right', on =["id_station"], indicator=True)
.query("_merge == 'right_only'"))

,id_station,libelle_carburant,code_postal,type_station,date_releve,prix,prix_moyen,indice,Aire de camping-cars,Automate CB,...,Restauration sur place,Restauration à emporter,Station de gonflage,Station de lavage,Toilettes publiques,Vente de fioul domestique,Vente de gaz domestique,Vente de pétrole lampant,rien,_merge
1955194,1000005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,1,0,0,1,0,0,right_only
1955195,1120003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,1,1,0,1,0,0,0,0,right_only
1955196,1200004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,1,right_only
1955197,1960003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,1,1,0,0,right_only
1955198,2000004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,right_only
1955199,2100003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,0,0,0,right_only
1955200,2100014,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,0,0,0,right_only
1955201,2130003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,1,1,0,1,0,0,0,0,right_only
1955202,2140004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,1,1,1,1,0,0,0,0,right_only
1955203,2190001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,0,0,0,0,1,0,0,right_only
1955204,2190002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,1,1,0,0,1,0,0,0,0,right_only
1955205,2200004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,1,0,0,right_only
1955206,2250003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,1,0,0,right_only
1955207,2300003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,0,0,0,0,0,right_only
1955208,2300005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,1,right_only
1955209,2400002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,1,0,0,0,right_only
1955210,2800002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,0,0,0,0,1,0,0,right_only
1955211,3100004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,1,0,0,right_only
1955212,3150002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,0,0,0,right_only
1955213,3390002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,1,1,1,1,0,0,right_only
1955214,3410003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,1,right_only
1955215,4130001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,0,0,0,0,right_only
1955216,4170001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,1,1,0,0,right_only
1955217,4210001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,0,0,0,0,1,0,0,right_only
1955218,4210002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,1,0,0,0,0,1,0,0,right_only
1955219,4300003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,0,0,1,0,0,right_only
1955220,4500002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,1,1,0,0,right_only
1955221,5000003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,1,0,0,0,right_only
1955222,5000011,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,0,0,1,0,0,right_only
1955223,5100005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,0,1,0,0,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1956311,95130002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,0,0,0,right_only
1956312,95190002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,1,0,0,0,right_only
1956313,95220004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,1,0,0,right_only
1956314,95230001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,0,0,1,0,0,right_only
1956315,95230002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,1,1,1,1,0,1,0,0,right_only
1956316,95230005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,1,1,0,1,0,0,right_only
1956317,95240001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,1,0,0,right_only
1956318,95250001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,0,0,0,right_only
1956319,95300001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,0,1,1,0,0,right_only
1956320,95310005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,1,right_only
1956321,95330001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,1,0,0,right_only
1956322,95330006,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,1,0,0,1,1,0,right_only
1956323,95370002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,0,0,0,0,right_only
1956324,95420004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,1,1,1,0,0,0,0,0,0,right_only
1956325,95430001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,0,0,0,right_only
1956326,95450001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,1,0,1,0,0,right_only
1956327,95450002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,1,0,0,right_only
1956328,95450004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,1,1,0,1,0,1,0,0,right_only
1956329,95470001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,1,0,0,0,0,right_only
1956330,95490003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,1,1,0,1,0,0,right_only
1956331,95500004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,0,1,0,0,right_only
1956332,95550001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,1,0,1,0,1,0,0,right_only
1956333,95570008,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,1,0,0,0,0,0,right_only
1956334,95740001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,0,0,1,0,0,right_only
1956335,95740003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,1,1,1,0,0,1,0,0,right_only
1956336,95800005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,1,1,0,1,0,0,right_only
1956337,95870003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,0,1,1,0,1,0,0,right_only
1956338,95870007,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,1,...,0,0,1,0,1,0,1,0,0,right_only
1956339,96600001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,1,0,0,right_only
1956340,99999001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,1,right_only

In [52]:
(model_df
.merge(matrice_services_df,how='outer', on =["id_station"], indicator=True)['_merge']
.value_counts())

both          1955194
left_only       12006
right_only       1147
Name: _merge, dtype: int64

In [41]:
from sklearn.linear_model import LinearRegression

In [56]:
model_services_df = model_df.merge(matrice_services_df, how='inner', on=["id_station"])

In [57]:
lr = LinearRegression()

In [54]:
matrice_services_df

,id_station,Aire de camping-cars,Automate CB,Baie de service auto,Bar,Boutique alimentaire,Boutique non alimentaire,Carburant qualité supérieure,Douches,Espace bébé / change,...,Relais colis,Restauration sur place,Restauration à emporter,Station de gonflage,Station de lavage,Toilettes publiques,Vente de fioul domestique,Vente de gaz domestique,Vente de pétrole lampant,rien
0,1000001,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1,1000002,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,1000004,0,0,0,0,1,1,1,0,0,...,1,0,0,1,0,1,1,1,0,0
3,1000005,0,1,0,0,1,1,1,0,0,...,0,0,0,1,1,0,0,1,0,0
4,1000006,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,1000007,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,1,0,0
6,1000008,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
7,1000009,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,1,0,0
8,1000010,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1000012,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,1000013,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1090001,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1100001,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
13,1100002,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14,1100003,0,1,1,0,1,1,1,0,0,...,0,0,0,1,0,0,1,0,0,0
15,1100004,0,0,0,0,1,1,1,0,0,...,0,0,1,1,0,1,0,1,0,0
16,1100006,0,1,0,1,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
17,1100007,0,1,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
18,1110001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,1120002,0,1,0,0,1,1,1,1,1,...,0,0,0,1,0,1,0,0,0,0
20,1120003,0,0,0,1,1,1,1,1,1,...,0,0,1,1,0,1,0,0,0,0
21,1120004,0,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
22,1120005,0,1,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0
23,1120006,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1120007,0,0,0,0,1,1,1,1,1,...,0,0,1,1,0,1,0,0,0,0
25,1120008,0,1,0,0,1,1,1,1,1,...,0,1,1,1,0,1,0,0,0,0
26,1130001,0,1,1,0,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
27,1130002,0,1,0,0,1,1,1,0,0,...,0,0,0,1,0,1,0,1,0,0
28,1130003,0,1,1,0,1,1,1,0,0,...,0,0,0,1,1,0,0,1,0,0
29,1140001,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12361,95570005,0,0,0,1,1,1,1,0,0,...,0,0,1,1,0,1,0,0,0,0
12362,95570007,0,1,0,0,0,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
12363,95570008,0,1,0,0,0,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
12364,95600001,0,1,0,0,1,1,1,0,0,...,0,0,0,1,0,0,0,1,0,0
12365,95600002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12366,95610005,0,0,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12367,95610006,0,0,1,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12368,95610007,0,0,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12369,95610008,0,0,1,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12370,95640001,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12371,95650001,0,1,0,0,1,1,1,0,0,...,1,0,0,1,0,0,0,1,0,0
12372,95650002,0,1,0,0,1,1,1,0,0,...,1,0,0,1,0,0,0,1,0,0
12373,95712001,0,0,0,0,1,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
12374,95712002,0,1,0,0,1,1,1,0,0,...,0,1,1,1,0,1,0,0,0,0
12375,95712003,0,0,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,0,0,0
12376,95712004,0,0,0,0,1,1,1,0,0,...,0,1,1,1,0,1,0,0,0,0
12377,95740001,0,1,0,0,1,1,1,0,0,...,0,0,0,1,0,0,0,1,0,0
12378,95740003,0,1,0,0,0,0,1,0,0,...,0,0,1,1,1,0,0,1,0,0
12379,95740004,0,1,0,0,1,0,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12380,95740005,0,0,0,0,1,1,1,0,0,...,0,0,0,1,1,0,0,1,0,0
12381,95800001,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12382,95800003,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12383,95800005,0,1,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12384,95800007,0,1,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12385,95870003,0,1,0,0,1,1,1,0,0,...,0,0,0,0,1,1,0,1,0,0
12386,95870005,0,0,0,0,1,1,1,0,0,...,0,0,0,1,1,1,0,1,0,0
12387,95870007,0,1,0,0,1,1,1,0,0,...,0,0,0,1,0,1,0,1,0,0
12388,95870009,0,1,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
12389,96600001,0,0,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
12390,99999001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [59]:
lr.fit(X=model_services_df[list(set(matrice_services_df)-{'id_station'})], y=model_services_df.indice)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [74]:
resultat=[(f, c) for f, c in zip(list(set(matrice_services_df.columns)-{'id_station'}), lr.coef_)]

In [71]:
pd.DataFrame(resultat, columns=['service', 'coefficient'].sort_values('Coefficient').plot(kind='barth'))

AttributeError: 'list' object has no attribute 'sort_values'

In [72]:
import seaborn as sns

In [75]:
resultat.plot(kind="barh")

AttributeError: 'list' object has no attribute 'plot'

## modelisation RF

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [80]:
rf = RandomForestRegressor()

In [81]:
rf.fit(X=model_services_df[list(set(matrice_services_df)-{'id_station'})], y=model_services_df.indice)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [85]:
resultat=[(f, c) for f, c in zip(list(set(matrice_services_df.columns)-{'id_station'}), rf.estimators_)]